"""add_IdMapping

Revision ID: 6ff78df305cf
Revises: 3bff20d0971d
Create Date: 2026-03-26 21:45:06.445083

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ff78df305cf'
down_revision: Union[str, Sequence[str], None] = '3bff20d0971d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('id_mapping',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.String(), nullable=False),
    sa.Column('faiss_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('person_id')
    )
    op.create_index(op.f('ix_id_mapping_id'), 'id_mapping', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_id_mapping_id'), table_name='id_mapping')
    op.drop_table('id_mapping')
    # ### end Alembic commands ###
