"""update_dim

Revision ID: 8adef9c1d208
Revises: 678d78b69cd5
Create Date: 2026-03-26 00:46:02.431116

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision: str = '8adef9c1d208'
down_revision: Union[str, Sequence[str], None] = '678d78b69cd5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('face_records', 'embedding',
               existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=128),
               type_=pgvector.sqlalchemy.vector.VECTOR(dim=512),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('face_records', 'embedding',
               existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=512),
               type_=pgvector.sqlalchemy.vector.VECTOR(dim=128),
               existing_nullable=False)
    # ### end Alembic commands ###
