"""update

Revision ID: ad0e5ff6c457
Revises: 6ff78df305cf
Create Date: 2026-03-26 21:50:19.512006

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad0e5ff6c457'
down_revision: Union[str, Sequence[str], None] = '6ff78df305cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_id_mapping_faiss_id'), 'id_mapping', ['faiss_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_id_mapping_faiss_id'), table_name='id_mapping')
    # ### end Alembic commands ###
