"""update

Revision ID: b53e4cdf1e92
Revises: 8adef9c1d208
Create Date: 2026-03-26 02:33:36.316255

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b53e4cdf1e92'
down_revision: Union[str, Sequence[str], None] = '8adef9c1d208'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('persons', sa.Column('hometown', sa.String(), nullable=True))
    op.add_column('persons', sa.Column('lost_year', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('persons', 'lost_year')
    op.drop_column('persons', 'hometown')
    # ### end Alembic commands ###
