groups:
  - name: beacons_alerts
    rules:
      - alert: HighCPU
        expr: 100 - (avg by(instance) (irate(node_cpu_seconds_total{mode="idle"}[5m])) * 100) > 80
        for: 10s
        labels:
          severity: warning
        annotations:
          summary: "High CPU usage on {{ $labels.instance }}"
          description: "CPU usage is {{ humanize $value }}% (threshold > 80%)."

      - alert: HighRAM
        expr: (1 - (node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes)) * 100 > 90
        for: 10s
        labels:
          severity: critical
        annotations:
          summary: "High RAM usage on {{ $labels.instance }}"
          description: "RAM usage is {{ humanize $value }}% (threshold > 90%)."

      - alert: HighDisk
        expr: (100 - node_filesystem_avail_bytes{mountpoint="/"}/node_filesystem_size_bytes{mountpoint="/"}*100) > 90
        for: 10s
        labels:
          severity: warning
        annotations:
          summary: "High Disk usage on {{ $labels.instance }}"
          description: "Disk usage on / is {{ humanize $value }}% (threshold > 90%)."

      - alert: ServiceDown
        expr: up == 0
        for: 10s
        labels:
          severity: critical
        annotations:
          summary: "Service {{ $labels.job }} down"
          description: "Service {{ $labels.job }} on {{ $labels.instance }} has been down for more than 10 seconds."
